name: release-please

on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: rp
        with:
          release-type: simple
          package-name: f1-telemetry-dashboard
          bump-minor-pre-major: true
          token: ${{ secrets.PEDRO_GITHUB_TOKEN }}

      - name: Get PR output
        if: steps.rp.outputs.releases_created
        run: |
          echo ${{ steps.rp.outputs.sha }}

      - uses: octokit/request-action@v2.1.9
        if: steps.rp.outputs.releases_created
        id: get_rp_commit
        with:
          route: GET /repos/{owner}/{repo}/commits/${{ steps.rp.outputs.sha }}
          owner: nearform
          repo: initium-cli
        env:
          GITHUB_TOKEN: ${{ secrets.PEDRO_GITHUB_TOKEN }}

      - if: steps.rp.outputs.releases_created
        run: "echo commit: '${{ steps.get_rp_commit.outputs.data }}'"
